### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by stasysp** [Zebraside/ML#1]
Я бы не стала так нещадно дропать все пропущенные значения, очень много теряем, нужно сначала посмотреть хотя бы долю пропущенных значений, а потом оценить, что можно выкинуть, а что лучше заполнить чем-либо.
Выделение категориальных признаков, вроде, прокатило на этих данных, но вернее это сделать по описанию датасета в начале =))

**Comment by Zebraside** [comment]
@stasysp 
![Untitled](https://user-images.githubusercontent.com/16067527/54820139-372a0800-4caf-11e9-830a-b81d405dcf64.png)

![image](https://user-images.githubusercontent.com/16067527/54820035-da2e5200-4cae-11e9-927f-94c41f4ce07d.png)

**Comment by stasysp** [comment]
:D
